/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  roslynatorSidebar: [
    { type: 'doc', id: 'roslynator/index', label: "Intro" },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Roslynator Guides',
        slug: 'roslynator/category/guides'
      },
      items: [
        'roslynator/configuration',
        'roslynator/analyzers-vs-refactorings',
        'roslynator/how-to-suppress-diagnostic',
        'roslynator/how-to-fix-all-diagnostics',
      ],
    },
    {
      type: 'category',
      label: 'Developers',
      link: {
        type: 'generated-index',
        title: 'Developers',
        slug: 'roslynator/developers'
      },
      items: [
        'roslynator/how-to-add-new-analyzer',
        'roslynator/how-to-add-new-refactoring',
        'roslynator/testing',
        'roslynator/how-to-update-documentation',
        {
          type: 'category',
          label: 'Metadata Reference',
          link: {
            type: 'generated-index',
            title: 'Metadata Reference',
            slug: 'roslynator/category/metadata'
          },
          items: [
            'roslynator/analyzer-metadata',
            'roslynator/refactoring-metadata',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Code Analysis Reference',
      link: {
        type: 'generated-index',
        title: 'Code Analysis Reference',
        slug: 'roslynator/category/code-analysis'
      },
      items: [
        {
          type: 'category',
          label: 'Analyzers',
          link: { type: 'doc', id: 'roslynator/analyzers' },
          items: [
            {
              type: 'autogenerated',
              dirName:   'roslynator/analyzers',
            },
          ],
        },
        {
          type: 'category',
          label: 'Refactorings',
          link: { type: 'doc', id: 'roslynator/refactorings' },
          items: [
            {
              type: 'autogenerated',
              dirName:   'roslynator/refactorings',
            },
          ],
        },
        {
          type: 'category',
          label: 'Fixes',
          link: { type: 'doc', id: 'roslynator/fixes' },
          items: [
            {
              type: 'autogenerated',
              dirName:   'roslynator/fixes',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      link: { type: 'doc', id: 'roslynator/cli' },
      items: [
        {
          type: 'category',
          label: 'Commands',
          link: { type: 'doc', id: 'roslynator/cli/commands' },
          items: [
            {
              type: 'autogenerated',
              dirName:   'roslynator/cli/commands',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '.NET API Reference',
      link: { type: 'doc', id: 'roslynator/ref' },
      items: [
        {
          type: 'autogenerated',
          dirName:   'roslynator/ref',
        },
      ],
    },
 ],
  orangSidebar: [
    {
      type: 'category',
      label: 'Orang CLI',
      link: { type: 'doc', id: 'orang/cli' },
      items: [
        {
          type: 'category',
          label: 'Commands',
          link: { type: 'doc', id: 'orang/cli/commands' },
          items: [
            {
              type: 'autogenerated',
              dirName:   'orang/cli/commands',
            },
          ],
        },
      ],
    },
  ],

  dotmarkdownSidebar: [
    {
      type: 'category',
      label: 'Intro',
      link: { type: 'doc', id: 'dotmarkdown/index' },
      items: [
        {
          type: 'category',
          label: 'DotMarkdown Reference',
          link: { type: 'doc', id: 'dotmarkdown/ref' },
          items: [
            {
              type: 'autogenerated',
              dirName:   'dotmarkdown/ref',
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
