on:
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  Configuration: Release
  TreatWarningsAsErrors: true
  WarningsNotAsErrors: 1591
  RunCodeAnalysis: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build_orang:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/DocumentationGenerator
    steps:
      - uses: actions/checkout@v3
        with:
          repository: josefpihrt/orang
          ref: feature/docusaurus
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: mkdir "_build"
      - run: dotnet "bin/Release/net7.0/Orang.DocumentationGenerator.dll" "_build" "data"
      - uses: actions/upload-artifact@v3
        with:
          name: orang
          path: src/DocumentationGenerator/_build

  build_roslynator_cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "src/CommandLine.DocumentationGenerator"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: josefpihrt/roslynator
          ref: feature/docs-docusaurus
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: mkdir "_build"
      - run: dotnet "bin/Release/net7.0/Roslynator.CommandLine.DocumentationGenerator.dll" "_build" "data" "help,migrate"
      - uses: actions/upload-artifact@v3
        with:
          name: roslynator_cli
          path: src/CommandLine.DocumentationGenerator/_build

  build_roslynator_ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: josefpihrt/roslynator
          ref: feature/docs-docusaurus
      # - run: dotnet restore src/CommandLine.sln
      # - run: dotnet build src/CommandLine.sln --no-restore
      - run: |
          ls src/CommandLine -R
          cd tools
          ls
          ./generate_ref_docs.ps1
        shell: pwsh
      - uses: actions/upload-artifact@v3
        with:
          name: roslynator_ref
          path: docs/api

  build_dotmarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: josefpihrt/roslynator
          ref: feature/docs-docusaurus
          path: roslynator
      - run: |
          dotnet restore
          dotnet build --no-restore
        working-directory: "roslynator/src/CommandLine"
      - uses: actions/checkout@v3
        with:
          repository: josefpihrt/dotmarkdown
          ref: feature/docusaurus
          path: main
      - run: ls
      - run: >
          "roslynator/src/CommandLine/bin/Release/net7.0/Roslynator" generate-doc "dotmarkdown/src/DotMarkdown.sln"
          --properties "Configuration=Release"
          --projects "DotMarkdown(netstandard1.3)"
          --heading "DotMarkdown Reference"
          -o _build
          --host docusaurus
          --group-by-common-namespace
          --ignored-common-parts content
          --max-derived-types 10
      - uses: actions/upload-artifact@v3
        with:
          name: dotmarkdown
          path: _build

  # build:
  #   needs: [ build_orang, build_roslynator_cli, build_roslynator_ref, build_dotmarkdown ]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: orang
  #         path: docs/orang/cli
  #     - run: ls docs/orang/cli

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: roslynator_cli
  #         path: docs/roslynator/cli
  #     - run: ls docs/roslynator/cli

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: roslynator_ref
  #         path: docs/roslynator/api
  #     - run: ls docs/roslynator/api

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: dotmarkdown
  #         path: docs/dotmarkdown/api
  #     - run: ls docs/dotmarkdown/api

  #     - run: npm install
  #     - run: npm run build
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: build
  #         path: build

  # deploy:
  #   needs: build
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #         path: build
  #     - name: Setup Pages
  #       uses: actions/configure-pages@v3
  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v2
  #       with:
  #         path: build
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v2
